<?php

return [
    ['id' => 'sq', 'name' => 'Albanian (Shqip)'],
    ['id' => 'ar', 'name' => 'Arabic (عربي)'],
    ['id' => 'az', 'name' => 'Azerbaijani (Azeri)'],
    ['id' => 'eu', 'name' => 'Basque (Euskara)'],
    ['id' => 'bs', 'name' => 'Bosnian (Bosanski)'],
    ['id' => 'bg', 'name' => 'Bulgarian (Български)'],
    ['id' => 'ca', 'name' => 'Catalan (Català)'],
    ['id' => 'hr', 'name' => 'Croatian (Hrvatski)'],
    ['id' => 'cs', 'name' => 'Czech (Čeština)'],
    ['id' => 'da', 'name' => 'Danish (Dansk)'],
    ['id' => 'nl', 'name' => 'Dutch (Nederlands)'],
    ['id' => 'en', 'name' => 'English'],
    ['id' => 'en-GB', 'name' => 'English (British)'],
    ['id' => 'et', 'name' => 'Estonian (Eesti)'],
    ['id' => 'fi', 'name' => 'Finnish (Suomi)'],
    ['id' => 'fr', 'name' => 'French (Français)'],
    ['id' => 'gl', 'name' => 'Galician (Galego)'],
    ['id' => 'de', 'name' => 'German (Deutsch)'],
    ['id' => 'el', 'name' => 'Greek (Ελληνικά)'],
    ['id' => 'he', 'name' => 'Hebrew (עברית)'],
    ['id' => 'hu', 'name' => 'Hungarian (Magyar)'],
    ['id' => 'id', 'name' => 'Indonesian (Bahasa Indonesia)'],
    ['id' => 'it', 'name' => 'Italian (Italiano)'],
    ['id' => 'ja', 'name' => 'Japanese (日本語)'],
    ['id' => 'ko', 'name' => 'Korean (한국어)'],
    ['id' => 'lv', 'name' => 'Latvian (Latviešu)'],
    ['id' => 'lt', 'name' => 'Lithuanian (lietuvių)'],
    ['id' => 'mk', 'name' => 'Macedonian (Македонски)'],
    ['id' => 'mn', 'name' => 'Mongolian (Монгол)'],
    ['id' => 'no', 'name' => 'Norwegian (Norsk bokmål)'],
    ['id' => 'fa', 'name' => 'Persian (پارسی)'],
    ['id' => 'pl', 'name' => 'Polish (Polski)'],
    ['id' => 'pt', 'name' => 'Portuguese (Português)'],
    ['id' => 'pt-BR', 'name' => 'Portuguese/Brasil (Português/Brasil)'],
    ['id' => 'ro', 'name' => 'Romanian (Română)'],
    ['id' => 'ru', 'name' => 'Russian (Русский)'],
    ['id' => 'sr-YU', 'name' => 'Serbian (Srpski)'],
    ['id' => 'sr', 'name' => 'Serbian Cyrillic (Српски)'],
    ['id' => 'zh', 'name' => 'Simplified Chinese (简体中文)'],
    ['id' => 'sk', 'name' => 'Slovak (Slovenčina)'],
    ['id' => 'sl', 'name' => 'Slovene (Slovenščina)'],
    ['id' => 'es', 'name' => 'Spanish (Español)'],
    ['id' => 'es-PA', 'name' => 'Spanish/Panama (Español/Panamá)'],
    ['id' => 'sv', 'name' => 'Swedish (Svenska)'],
    ['id' => 'th', 'name' => 'Thai (ไทย)'],
    ['id' => 'zh-TW', 'name' => 'Traditional Chinese (繁體中文)'],
    ['id' => 'tr', 'name' => 'Turkish (Türkçe)'],
    ['id' => 'uk', 'name' => 'Ukrainian (Українська)'],
    ['id' => 'vi', 'name' => 'Vietnamese (Tiếng Việt)']
];